---
apiVersion: v1
kind: Secret
metadata:
  name: master-cert
  namespace: catv
data:
  ca.crt:
  tls.crt:
  tls.key:
type: kubernetes.io/tls

---
apiVersion: v1
kind: Secret
metadata:
  name: catv-master-credentials
  namespace: catv
data:
  clickhouse-password: ZGVmYXVsdA==
  weather-password: d2luZG1pbGw3OCgp
type: Opaque
