---
apiVersion: v1
kind: Service
metadata:
  name: catv-master
  namespace: catv
  labels:
    app: catv-master
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 31001
    - name: tx-daily
      protocol: UDP
      port: 50001
      targetPort: 50001
    - name: tx-diagnostic
      protocol: UDP
      port: 50003
      targetPort: 50003
    - name: tx-n-q-t
      protocol: UDP
      port: 50004
      targetPort: 50004
    - name: tx-periodic
      protocol: UDP
      port: 50000
      targetPort: 50000
    - name: tx-q-m
      protocol: UDP
      port: 50005
      targetPort: 50005
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: catv-master
