---
apiVersion: v1
kind: Service
metadata:
  name: pharos-master
  namespace: pharos
  labels:
    app: pharos-master
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30996
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30998
    - name: sample-plugin01
      protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 31005
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: pharos-master
