package main

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"text/template"
)

const tmpl = `// Code generated by meta/scripts/generate-metadata. DO NOT EDIT.

package main

import (
{{- if .Extensions}}
{{- range .Extensions}}
	_ "ntels.com/pharos/extensions/{{.}}"
{{- end}}
{{- else}}
	// No backend extensions found
{{- end}}
)
`

type SiteModeConfig struct {
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Icon           string   `json:"icon"`
	MenuVariables  []string `json:"menuVariables"`
	LoginExtension string   `json:"login-extension"`
	Extensions     []string `json:"extensions"`
}

func main() {
	siteMode := os.Getenv("SITE_MODE")
	if siteMode == "" {
		siteMode = "default"
	}

	fmt.Printf("Generating extensions for SITE_MODE: %s\n", siteMode)

	// Find project root
	projectRoot, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(projectRoot, "go.work")); err == nil {
			break
		}
		projectRoot = filepath.Dir(projectRoot)
	}

	targetExtensions := resolveSiteModeToExtensions(projectRoot, siteMode)

	extensionsDir := filepath.Join(projectRoot, "extensions")

	// Scan extensions
	var extensions []string
	for _, extName := range targetExtensions {
		if extName == "all" {
			// Recursively scan all subdirectories
			scanExtensions(extensionsDir, "", &extensions)
			break
		}

		extFile := filepath.Join(extensionsDir, extName, "extension.go")
		if _, err := os.Stat(extFile); err == nil {
			extensions = append(extensions, extName)
		}
	}

	// Generate file directly in core/cmd/pharos (no intermediate file needed)
	importFile := filepath.Join(projectRoot, "core", "cmd", "pharos", "import_extensions.go")
	f, _ := os.Create(importFile)
	defer func() { _ = f.Close() }()

	t := template.Must(template.New("imports").Parse(tmpl))
	err := t.Execute(f, map[string]interface{}{
		"Extensions": extensions,
	})
	if err != nil {
		slog.Error("template execute failed", "err", err)
		return
	}

	fmt.Printf("✓ Generated import_extensions.go (%d extension%s for SITE_MODE: %s)\n",
		len(extensions),
		map[bool]string{true: "", false: "s"}[len(extensions) == 1],
		siteMode)
}

func scanExtensions(dir, relativePath string, extensions *[]string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		slog.Error("failed to read directory", "dir", dir, "err", err)
		return
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		currentPath := filepath.Join(dir, entry.Name())
		currentRelative := entry.Name()
		if relativePath != "" {
			currentRelative = filepath.Join(relativePath, entry.Name())
		}

		extGoFile := filepath.Join(currentPath, "extension.go")
		frontendPkg := filepath.Join(currentPath, "frontend", "package.json")

		// Check if both backend and frontend parts exist
		_, errGo := os.Stat(extGoFile)
		_, errPkg := os.Stat(frontendPkg)

		if errGo == nil && errPkg == nil {
			*extensions = append(*extensions, currentRelative)
		} else {
			// No extension.go, continue scanning subdirectories
			scanExtensions(currentPath, currentRelative, extensions)
		}
	}
}

func resolveSiteModeToExtensions(projectRoot, siteMode string) []string {
	configPath := filepath.Join(projectRoot, "meta", "configs", siteMode+".json")
	data, err := os.ReadFile(configPath)
	if err != nil {
		slog.Error("failed to read config", "err", err, "path", configPath)
		os.Exit(1)
	}

	var config SiteModeConfig
	if err := json.Unmarshal(data, &config); err != nil {
		slog.Error("failed to unmarshal config", "err", err)
		return []string{siteMode}
	}

	if config.LoginExtension == "" {
		slog.Error("login-extension is required", "mode", siteMode)
		os.Exit(1)
	}

	var allExtensions []string
	allExtensions = append(allExtensions, config.LoginExtension)
	allExtensions = append(allExtensions, config.Extensions...)
	return allExtensions
}
