/**
 * Extension Loader (AUTO-GENERATED)
 * Generated by: pnpm generate:extensions
 */

// ========================================
// AUTO-GENERATED IMPORTS
// ========================================
// Extension: example
import '@pharos/extension-example';
// ========================================
// END AUTO-GENERATED
// ========================================
